from tkinter import *

def click(event):

    text=event.widget.cget("text")
    if text=="=":
        if entryvalue.get().isdigit():
            value=int(entryvalue.get())
        else:
            value=eval(entry.get())
        entryvalue.set(value)
        entry.update()
    elif text=="AC":
        entryvalue.set("")
        entry.update()
    else:
        entryvalue.set(entryvalue.get()+text)
        entry.update()

     
root=Tk()
root.title("Calculator")
root.geometry("500x800")
entryvalue=StringVar()
entry=Entry(root, textvariable=entryvalue , font="roboto 22 bold")
entry.pack(fill=X ,padx=10,pady=5 )
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="9" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="8" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="8" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
f.pack()
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="6" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="5" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="4" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
f.pack()
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="3" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="2" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="1" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=10, pady=5)
b.bind("<Button-1>", click)
f.pack()
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="+" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=11, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="0" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=11, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="-" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=11, pady=5)
b.bind("<Button-1>", click)
f.pack()
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="/" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=8, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="*" , relief=RAISED, font="roboto 26 bold")
b.pack(side=LEFT , padx=8, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="AC", relief=RAISED, font="roboto 25 bold")
b.pack(side=LEFT , padx=8, pady=5)
b.bind("<Button-1>", click)
f.pack()
f=Frame(root, bg="grey", borderwidth=10)
b=Button(f, text="=", relief=RAISED, font="roboto 26 bold")
b.pack(padx=10, pady=5)
b.bind("<Button-1>", click)
f.pack()
root.mainloop()
